version: "3.3"
services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    #network_mode: "bridge"
    ports:
        - "8096:8096"
    restart: "unless-stopped"
    volumes:
      - /media/Elements/jellyfin/config:/config
      - /media/Elements/jellyfin/cache:/cache
      - /media/Elements/media:/media
    networks: 
      - backend

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - BASE_URL=/ombi #optional
    volumes:
      - /media/Elements/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    networks:
      - backend
  
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - UMASK_SET=022 #optional
    volumes:
      - /media/Elements/sonarr/config:/config
      - /media/Elements/transmission/downloads:/downloads
      - /media/Elements/media/Series:/tv

    ports:
      - 8989:8989
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=user  #optional
      - PASS=password #optional
    volumes:
      - /media/Elements/transmission/data:/config
      - /media/Elements/transmission/downloads:/downloads
      - /media/Elements/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - backend

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /media/Elements/radarr/config:/config
      - /media/Elements/media/Films:/movies #optional
      - /media/Elements/transmission/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - AUTO_UPDATE=true 
    volumes:
      - /media/Elements/jackett/config:/config
      - /media/Elements/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

networks:
  backend:
    driver: bridge
